server:
  port: 0

spring:
  application:
    name: payment-service

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver #org.h2.Driver
    url: jdbc:mysql://localhost:3306/ecommercePayment?useSSL=false #jdbc:h2:mem:mydb #testdb
    username: root #sa
    password: A1b2c347 #1234

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
